"""Preset data for tracks, teams, and drivers."""

from __future__ import annotations

from datetime import date

TEAM_COLORS: dict[str, str] = {
    "Red Bull": "#3671C6",
    "Ferrari": "#E8002D",
    "Mercedes": "#27F4D2",
    "McLaren": "#FF8000",
    "Aston Martin": "#229971",
    "Alpine": "#FF87BC",
    "Williams": "#64C4FF",
    "RB": "#6692FF",
    "Kick Sauber": "#52E252",
    "Haas": "#B6BABD",
}

PRESET_TRACKS = [
    {
        "name": "Monaco",
        "country": "Monaco",
        "total_laps": 78,
        "base_lap_time": 74.0,
        "pit_loss_time": 24.0,
        "drs_zones": 1,
        "overtake_difficulty": 2.0,
        "safety_car_probability": 0.05,
    },
    {
        "name": "Silverstone",
        "country": "United Kingdom",
        "total_laps": 52,
        "base_lap_time": 88.0,
        "pit_loss_time": 22.0,
        "drs_zones": 2,
        "overtake_difficulty": 0.8,
        "safety_car_probability": 0.03,
    },
    {
        "name": "Monza",
        "country": "Italy",
        "total_laps": 53,
        "base_lap_time": 82.0,
        "pit_loss_time": 25.0,
        "drs_zones": 2,
        "overtake_difficulty": 0.7,
        "safety_car_probability": 0.03,
    },
    {
        "name": "Spa-Francorchamps",
        "country": "Belgium",
        "total_laps": 44,
        "base_lap_time": 106.0,
        "pit_loss_time": 22.0,
        "drs_zones": 2,
        "overtake_difficulty": 0.8,
        "safety_car_probability": 0.04,
    },
    {
        "name": "Suzuka",
        "country": "Japan",
        "total_laps": 53,
        "base_lap_time": 91.0,
        "pit_loss_time": 23.0,
        "drs_zones": 1,
        "overtake_difficulty": 1.2,
        "safety_car_probability": 0.03,
    },
    {
        "name": "Singapore",
        "country": "Singapore",
        "total_laps": 62,
        "base_lap_time": 98.0,
        "pit_loss_time": 26.0,
        "drs_zones": 3,
        "overtake_difficulty": 1.5,
        "safety_car_probability": 0.06,
    },
    {
        "name": "Bahrain",
        "country": "Bahrain",
        "total_laps": 57,
        "base_lap_time": 92.0,
        "pit_loss_time": 22.0,
        "drs_zones": 3,
        "overtake_difficulty": 0.7,
        "safety_car_probability": 0.02,
    },
    {
        "name": "Jeddah",
        "country": "Saudi Arabia",
        "total_laps": 50,
        "base_lap_time": 89.0,
        "pit_loss_time": 23.0,
        "drs_zones": 3,
        "overtake_difficulty": 0.8,
        "safety_car_probability": 0.05,
    },
    {
        "name": "COTA",
        "country": "United States",
        "total_laps": 56,
        "base_lap_time": 97.0,
        "pit_loss_time": 22.0,
        "drs_zones": 2,
        "overtake_difficulty": 0.9,
        "safety_car_probability": 0.03,
    },
    {
        "name": "Interlagos",
        "country": "Brazil",
        "total_laps": 71,
        "base_lap_time": 72.0,
        "pit_loss_time": 22.0,
        "drs_zones": 2,
        "overtake_difficulty": 0.8,
        "safety_car_probability": 0.04,
    },
]

PRESET_DRIVERS = [
    {"name": "Max Verstappen", "team": "Red Bull", "skill": -0.8},
    {"name": "Sergio Perez", "team": "Red Bull", "skill": -0.1},
    {"name": "Charles Leclerc", "team": "Ferrari", "skill": -0.5},
    {"name": "Carlos Sainz", "team": "Ferrari", "skill": -0.3},
    {"name": "Lewis Hamilton", "team": "Mercedes", "skill": -0.5},
    {"name": "George Russell", "team": "Mercedes", "skill": -0.3},
    {"name": "Lando Norris", "team": "McLaren", "skill": -0.6},
    {"name": "Oscar Piastri", "team": "McLaren", "skill": -0.4},
    {"name": "Fernando Alonso", "team": "Aston Martin", "skill": -0.2},
    {"name": "Lance Stroll", "team": "Aston Martin", "skill": 0.1},
    {"name": "Pierre Gasly", "team": "Alpine", "skill": -0.1},
    {"name": "Esteban Ocon", "team": "Alpine", "skill": -0.0},
    {"name": "Alexander Albon", "team": "Williams", "skill": -0.1},
    {"name": "Logan Sargeant", "team": "Williams", "skill": 0.4},
    {"name": "Yuki Tsunoda", "team": "RB", "skill": -0.1},
    {"name": "Daniel Ricciardo", "team": "RB", "skill": 0.0},
    {"name": "Valtteri Bottas", "team": "Kick Sauber", "skill": 0.0},
    {"name": "Zhou Guanyu", "team": "Kick Sauber", "skill": 0.2},
    {"name": "Kevin Magnussen", "team": "Haas", "skill": 0.1},
    {"name": "Nico Hulkenberg", "team": "Haas", "skill": 0.0},
]

# ─── 2026 Season Data ───────────────────────────────────────────────────────

TEAM_COLORS_2026: dict[str, str] = {
    "Red Bull": "#3671C6",
    "Ferrari": "#E8002D",
    "Mercedes": "#27F4D2",
    "McLaren": "#FF8000",
    "Aston Martin": "#229971",
    "Alpine": "#FF87BC",
    "Williams": "#64C4FF",
    "Racing Bulls": "#6692FF",
    "Sauber": "#52E252",
    "Haas": "#B6BABD",
    "Cadillac": "#C0A44D",
}

DRIVERS_2026 = [
    {"name": "Max Verstappen", "team": "Red Bull", "skill": -0.8, "number": 1},
    {"name": "Isack Hadjar", "team": "Red Bull", "skill": 0.1, "number": 6},
    {"name": "Charles Leclerc", "team": "Ferrari", "skill": -0.5, "number": 16},
    {"name": "Lewis Hamilton", "team": "Ferrari", "skill": -0.5, "number": 44},
    {"name": "George Russell", "team": "Mercedes", "skill": -0.3, "number": 63},
    {"name": "Andrea Kimi Antonelli", "team": "Mercedes", "skill": -0.1, "number": 12},
    {"name": "Lando Norris", "team": "McLaren", "skill": -0.6, "number": 4},
    {"name": "Oscar Piastri", "team": "McLaren", "skill": -0.4, "number": 81},
    {"name": "Fernando Alonso", "team": "Aston Martin", "skill": -0.2, "number": 14},
    {"name": "Lance Stroll", "team": "Aston Martin", "skill": 0.1, "number": 18},
    {"name": "Pierre Gasly", "team": "Alpine", "skill": -0.1, "number": 10},
    {"name": "Jack Doohan", "team": "Alpine", "skill": 0.2, "number": 7},
    {"name": "Alexander Albon", "team": "Williams", "skill": -0.1, "number": 23},
    {"name": "Carlos Sainz", "team": "Williams", "skill": -0.3, "number": 55},
    {"name": "Yuki Tsunoda", "team": "Racing Bulls", "skill": -0.1, "number": 22},
    {"name": "Arvid Lindblad", "team": "Racing Bulls", "skill": 0.2, "number": 27},
    {"name": "Nico Hulkenberg", "team": "Sauber", "skill": 0.0, "number": 27},
    {"name": "Gabriel Bortoleto", "team": "Sauber", "skill": 0.1, "number": 5},
    {"name": "Esteban Ocon", "team": "Haas", "skill": 0.0, "number": 31},
    {"name": "Oliver Bearman", "team": "Haas", "skill": 0.1, "number": 87},
    {"name": "Sergio Perez", "team": "Cadillac", "skill": -0.1, "number": 11},
    {"name": "Valtteri Bottas", "team": "Cadillac", "skill": 0.0, "number": 77},
]

CALENDAR_2026 = [
    {"round": 1, "name": "Australian Grand Prix", "track": "Albert Park", "country": "Australia",
     "date": date(2026, 3, 15), "lat": -37.8497, "lon": 144.9680,
     "total_laps": 58, "base_lap_time": 80.0, "pit_loss": 22.0, "drs_zones": 3,
     "overtake_difficulty": 0.9, "sc_probability": 0.04},
    {"round": 2, "name": "Chinese Grand Prix", "track": "Shanghai", "country": "China",
     "date": date(2026, 3, 29), "lat": 31.3389, "lon": 121.2198,
     "total_laps": 56, "base_lap_time": 96.0, "pit_loss": 22.0, "drs_zones": 2,
     "overtake_difficulty": 0.8, "sc_probability": 0.03},
    {"round": 3, "name": "Japanese Grand Prix", "track": "Suzuka", "country": "Japan",
     "date": date(2026, 4, 12), "lat": 34.8431, "lon": 136.5407,
     "total_laps": 53, "base_lap_time": 91.0, "pit_loss": 23.0, "drs_zones": 1,
     "overtake_difficulty": 1.2, "sc_probability": 0.03},
    {"round": 4, "name": "Bahrain Grand Prix", "track": "Bahrain", "country": "Bahrain",
     "date": date(2026, 4, 19), "lat": 26.0325, "lon": 50.5106,
     "total_laps": 57, "base_lap_time": 92.0, "pit_loss": 22.0, "drs_zones": 3,
     "overtake_difficulty": 0.7, "sc_probability": 0.02},
    {"round": 5, "name": "Saudi Arabian Grand Prix", "track": "Jeddah", "country": "Saudi Arabia",
     "date": date(2026, 5, 3), "lat": 21.6319, "lon": 39.1044,
     "total_laps": 50, "base_lap_time": 89.0, "pit_loss": 23.0, "drs_zones": 3,
     "overtake_difficulty": 0.8, "sc_probability": 0.05},
    {"round": 6, "name": "Miami Grand Prix", "track": "Miami", "country": "United States",
     "date": date(2026, 5, 17), "lat": 25.9581, "lon": -80.2389,
     "total_laps": 57, "base_lap_time": 91.0, "pit_loss": 22.0, "drs_zones": 3,
     "overtake_difficulty": 0.8, "sc_probability": 0.04},
    {"round": 7, "name": "Emilia Romagna Grand Prix", "track": "Imola", "country": "Italy",
     "date": date(2026, 5, 31), "lat": 44.3439, "lon": 11.7167,
     "total_laps": 63, "base_lap_time": 76.0, "pit_loss": 24.0, "drs_zones": 1,
     "overtake_difficulty": 1.3, "sc_probability": 0.03},
    {"round": 8, "name": "Monaco Grand Prix", "track": "Monaco", "country": "Monaco",
     "date": date(2026, 6, 7), "lat": 43.7347, "lon": 7.4206,
     "total_laps": 78, "base_lap_time": 74.0, "pit_loss": 24.0, "drs_zones": 1,
     "overtake_difficulty": 2.0, "sc_probability": 0.05},
    {"round": 9, "name": "Spanish Grand Prix", "track": "Barcelona", "country": "Spain",
     "date": date(2026, 6, 21), "lat": 41.5700, "lon": 2.2611,
     "total_laps": 66, "base_lap_time": 78.0, "pit_loss": 22.0, "drs_zones": 2,
     "overtake_difficulty": 1.0, "sc_probability": 0.02},
    {"round": 10, "name": "Canadian Grand Prix", "track": "Montreal", "country": "Canada",
     "date": date(2026, 7, 5), "lat": 45.5017, "lon": -73.5228,
     "total_laps": 70, "base_lap_time": 75.0, "pit_loss": 22.0, "drs_zones": 2,
     "overtake_difficulty": 0.9, "sc_probability": 0.05},
    {"round": 11, "name": "Austrian Grand Prix", "track": "Red Bull Ring", "country": "Austria",
     "date": date(2026, 7, 12), "lat": 47.2197, "lon": 14.7647,
     "total_laps": 71, "base_lap_time": 66.0, "pit_loss": 21.0, "drs_zones": 2,
     "overtake_difficulty": 0.8, "sc_probability": 0.03},
    {"round": 12, "name": "British Grand Prix", "track": "Silverstone", "country": "United Kingdom",
     "date": date(2026, 7, 19), "lat": 52.0786, "lon": -1.0169,
     "total_laps": 52, "base_lap_time": 88.0, "pit_loss": 22.0, "drs_zones": 2,
     "overtake_difficulty": 0.8, "sc_probability": 0.03},
    {"round": 13, "name": "Belgian Grand Prix", "track": "Spa-Francorchamps", "country": "Belgium",
     "date": date(2026, 8, 2), "lat": 50.4372, "lon": 5.9714,
     "total_laps": 44, "base_lap_time": 106.0, "pit_loss": 22.0, "drs_zones": 2,
     "overtake_difficulty": 0.8, "sc_probability": 0.04},
    {"round": 14, "name": "Hungarian Grand Prix", "track": "Hungaroring", "country": "Hungary",
     "date": date(2026, 8, 9), "lat": 47.5789, "lon": 19.2486,
     "total_laps": 70, "base_lap_time": 79.0, "pit_loss": 23.0, "drs_zones": 1,
     "overtake_difficulty": 1.5, "sc_probability": 0.02},
    {"round": 15, "name": "Dutch Grand Prix", "track": "Zandvoort", "country": "Netherlands",
     "date": date(2026, 8, 30), "lat": 52.3888, "lon": 4.5409,
     "total_laps": 72, "base_lap_time": 72.0, "pit_loss": 22.0, "drs_zones": 1,
     "overtake_difficulty": 1.6, "sc_probability": 0.03},
    {"round": 16, "name": "Italian Grand Prix", "track": "Monza", "country": "Italy",
     "date": date(2026, 9, 6), "lat": 45.6156, "lon": 9.2811,
     "total_laps": 53, "base_lap_time": 82.0, "pit_loss": 25.0, "drs_zones": 2,
     "overtake_difficulty": 0.7, "sc_probability": 0.03},
    {"round": 17, "name": "Azerbaijan Grand Prix", "track": "Baku", "country": "Azerbaijan",
     "date": date(2026, 9, 20), "lat": 40.3725, "lon": 49.8533,
     "total_laps": 51, "base_lap_time": 103.0, "pit_loss": 24.0, "drs_zones": 2,
     "overtake_difficulty": 0.8, "sc_probability": 0.06},
    {"round": 18, "name": "Singapore Grand Prix", "track": "Singapore", "country": "Singapore",
     "date": date(2026, 10, 4), "lat": 1.2914, "lon": 103.8640,
     "total_laps": 62, "base_lap_time": 98.0, "pit_loss": 26.0, "drs_zones": 3,
     "overtake_difficulty": 1.5, "sc_probability": 0.06},
    {"round": 19, "name": "United States Grand Prix", "track": "COTA", "country": "United States",
     "date": date(2026, 10, 18), "lat": 30.1328, "lon": -97.6411,
     "total_laps": 56, "base_lap_time": 97.0, "pit_loss": 22.0, "drs_zones": 2,
     "overtake_difficulty": 0.9, "sc_probability": 0.03},
    {"round": 20, "name": "Mexico City Grand Prix", "track": "Mexico City", "country": "Mexico",
     "date": date(2026, 10, 25), "lat": 19.4042, "lon": -99.0907,
     "total_laps": 71, "base_lap_time": 78.0, "pit_loss": 23.0, "drs_zones": 3,
     "overtake_difficulty": 0.8, "sc_probability": 0.04},
    {"round": 21, "name": "Brazilian Grand Prix", "track": "Interlagos", "country": "Brazil",
     "date": date(2026, 11, 8), "lat": -23.7036, "lon": -46.6997,
     "total_laps": 71, "base_lap_time": 72.0, "pit_loss": 22.0, "drs_zones": 2,
     "overtake_difficulty": 0.8, "sc_probability": 0.04},
    {"round": 22, "name": "Las Vegas Grand Prix", "track": "Las Vegas", "country": "United States",
     "date": date(2026, 11, 22), "lat": 36.1147, "lon": -115.1728,
     "total_laps": 50, "base_lap_time": 95.0, "pit_loss": 23.0, "drs_zones": 2,
     "overtake_difficulty": 0.8, "sc_probability": 0.04},
    {"round": 23, "name": "Qatar Grand Prix", "track": "Lusail", "country": "Qatar",
     "date": date(2026, 11, 29), "lat": 25.4900, "lon": 51.4542,
     "total_laps": 57, "base_lap_time": 86.0, "pit_loss": 22.0, "drs_zones": 2,
     "overtake_difficulty": 0.8, "sc_probability": 0.03},
    {"round": 24, "name": "Abu Dhabi Grand Prix", "track": "Yas Marina", "country": "UAE",
     "date": date(2026, 12, 6), "lat": 24.4672, "lon": 54.6031,
     "total_laps": 58, "base_lap_time": 87.0, "pit_loss": 22.0, "drs_zones": 2,
     "overtake_difficulty": 0.9, "sc_probability": 0.02},
]

POINTS_SYSTEM: dict[int, int] = {
    1: 25, 2: 18, 3: 15, 4: 12, 5: 10, 6: 8, 7: 6, 8: 4, 9: 2, 10: 1,
}

# Historical F1 season stats (2020-2025) — official F1 standings data
# Key: (year, driver_name) -> {wins, podiums, points, avg_pos}
HISTORICAL_STATS: dict[tuple[int, str], dict] = {
    # ── 2020 (17 races) ──
    (2020, "Lewis Hamilton"):    {"wins": 11, "podiums": 14, "points": 347.0, "avg_pos": 1.9},
    (2020, "Valtteri Bottas"):   {"wins": 2,  "podiums": 11, "points": 223.0, "avg_pos": 4.3},
    (2020, "Max Verstappen"):    {"wins": 2,  "podiums": 11, "points": 214.0, "avg_pos": 2.4},
    (2020, "Sergio Perez"):      {"wins": 1,  "podiums": 2,  "points": 125.0, "avg_pos": 6.5},
    (2020, "Daniel Ricciardo"):  {"wins": 0,  "podiums": 2,  "points": 119.0, "avg_pos": 6.8},
    (2020, "Carlos Sainz"):      {"wins": 0,  "podiums": 1,  "points": 105.0, "avg_pos": 6.8},
    (2020, "Alexander Albon"):   {"wins": 0,  "podiums": 2,  "points": 105.0, "avg_pos": 7.8},
    (2020, "Charles Leclerc"):   {"wins": 0,  "podiums": 2,  "points": 98.0,  "avg_pos": 7.0},
    (2020, "Lando Norris"):      {"wins": 0,  "podiums": 1,  "points": 97.0,  "avg_pos": 7.8},
    (2020, "Pierre Gasly"):      {"wins": 1,  "podiums": 1,  "points": 75.0,  "avg_pos": 8.3},
    (2020, "Lance Stroll"):      {"wins": 0,  "podiums": 2,  "points": 75.0,  "avg_pos": 7.0},
    (2020, "Esteban Ocon"):      {"wins": 0,  "podiums": 1,  "points": 62.0,  "avg_pos": 8.3},
    (2020, "Nico Hulkenberg"):   {"wins": 0,  "podiums": 0,  "points": 10.0,  "avg_pos": 7.5},
    (2020, "George Russell"):    {"wins": 0,  "podiums": 0,  "points": 3.0,   "avg_pos": 14.6},
    (2020, "Kevin Magnussen"):   {"wins": 0,  "podiums": 0,  "points": 1.0,   "avg_pos": 14.7},
    # ── 2021 (22 races) ──
    (2021, "Max Verstappen"):    {"wins": 10, "podiums": 18, "points": 395.5, "avg_pos": 2.7},
    (2021, "Lewis Hamilton"):    {"wins": 8,  "podiums": 17, "points": 387.5, "avg_pos": 2.8},
    (2021, "Valtteri Bottas"):   {"wins": 1,  "podiums": 11, "points": 226.0, "avg_pos": 5.0},
    (2021, "Sergio Perez"):      {"wins": 1,  "podiums": 5,  "points": 190.0, "avg_pos": 6.6},
    (2021, "Carlos Sainz"):      {"wins": 0,  "podiums": 4,  "points": 164.5, "avg_pos": 6.5},
    (2021, "Lando Norris"):      {"wins": 0,  "podiums": 4,  "points": 160.0, "avg_pos": 6.6},
    (2021, "Charles Leclerc"):   {"wins": 0,  "podiums": 1,  "points": 159.0, "avg_pos": 6.6},
    (2021, "Daniel Ricciardo"):  {"wins": 1,  "podiums": 1,  "points": 115.0, "avg_pos": 8.1},
    (2021, "Pierre Gasly"):      {"wins": 0,  "podiums": 1,  "points": 110.0, "avg_pos": 7.7},
    (2021, "Fernando Alonso"):   {"wins": 0,  "podiums": 1,  "points": 81.0,  "avg_pos": 9.1},
    (2021, "Esteban Ocon"):      {"wins": 1,  "podiums": 1,  "points": 74.0,  "avg_pos": 9.2},
    (2021, "Lance Stroll"):      {"wins": 0,  "podiums": 0,  "points": 34.0,  "avg_pos": 10.8},
    (2021, "Yuki Tsunoda"):      {"wins": 0,  "podiums": 0,  "points": 32.0,  "avg_pos": 11.7},
    (2021, "George Russell"):    {"wins": 0,  "podiums": 1,  "points": 16.0,  "avg_pos": 12.8},
    # ── 2022 (22 races) ──
    (2022, "Max Verstappen"):    {"wins": 15, "podiums": 17, "points": 454.0, "avg_pos": 2.8},
    (2022, "Charles Leclerc"):   {"wins": 3,  "podiums": 11, "points": 308.0, "avg_pos": 3.3},
    (2022, "Sergio Perez"):      {"wins": 2,  "podiums": 11, "points": 305.0, "avg_pos": 4.0},
    (2022, "George Russell"):    {"wins": 1,  "podiums": 8,  "points": 275.0, "avg_pos": 4.4},
    (2022, "Carlos Sainz"):      {"wins": 1,  "podiums": 9,  "points": 246.0, "avg_pos": 3.5},
    (2022, "Lewis Hamilton"):    {"wins": 0,  "podiums": 9,  "points": 240.0, "avg_pos": 5.4},
    (2022, "Lando Norris"):      {"wins": 0,  "podiums": 1,  "points": 122.0, "avg_pos": 7.8},
    (2022, "Esteban Ocon"):      {"wins": 0,  "podiums": 0,  "points": 92.0,  "avg_pos": 8.2},
    (2022, "Fernando Alonso"):   {"wins": 0,  "podiums": 0,  "points": 81.0,  "avg_pos": 8.7},
    (2022, "Valtteri Bottas"):   {"wins": 0,  "podiums": 0,  "points": 49.0,  "avg_pos": 10.4},
    (2022, "Daniel Ricciardo"):  {"wins": 0,  "podiums": 0,  "points": 37.0,  "avg_pos": 11.6},
    (2022, "Kevin Magnussen"):   {"wins": 0,  "podiums": 0,  "points": 25.0,  "avg_pos": 13.2},
    (2022, "Pierre Gasly"):      {"wins": 0,  "podiums": 0,  "points": 23.0,  "avg_pos": 11.6},
    (2022, "Lance Stroll"):      {"wins": 0,  "podiums": 0,  "points": 18.0,  "avg_pos": 11.5},
    (2022, "Yuki Tsunoda"):      {"wins": 0,  "podiums": 0,  "points": 12.0,  "avg_pos": 13.1},
    (2022, "Zhou Guanyu"):       {"wins": 0,  "podiums": 0,  "points": 6.0,   "avg_pos": 12.9},
    (2022, "Alexander Albon"):   {"wins": 0,  "podiums": 0,  "points": 4.0,   "avg_pos": 12.8},
    (2022, "Nico Hulkenberg"):   {"wins": 0,  "podiums": 0,  "points": 0.0,   "avg_pos": 14.5},
    # ── 2023 (22 races) ──
    (2023, "Max Verstappen"):    {"wins": 19, "podiums": 21, "points": 575.0, "avg_pos": 1.3},
    (2023, "Sergio Perez"):      {"wins": 2,  "podiums": 9,  "points": 285.0, "avg_pos": 4.5},
    (2023, "Lewis Hamilton"):    {"wins": 0,  "podiums": 6,  "points": 234.0, "avg_pos": 4.9},
    (2023, "Fernando Alonso"):   {"wins": 0,  "podiums": 8,  "points": 206.0, "avg_pos": 5.6},
    (2023, "Charles Leclerc"):   {"wins": 0,  "podiums": 6,  "points": 206.0, "avg_pos": 4.9},
    (2023, "Lando Norris"):      {"wins": 0,  "podiums": 7,  "points": 205.0, "avg_pos": 7.4},
    (2023, "Carlos Sainz"):      {"wins": 1,  "podiums": 3,  "points": 200.0, "avg_pos": 6.3},
    (2023, "George Russell"):    {"wins": 0,  "podiums": 2,  "points": 175.0, "avg_pos": 6.6},
    (2023, "Oscar Piastri"):     {"wins": 0,  "podiums": 2,  "points": 97.0,  "avg_pos": 9.6},
    (2023, "Lance Stroll"):      {"wins": 0,  "podiums": 0,  "points": 74.0,  "avg_pos": 9.3},
    (2023, "Pierre Gasly"):      {"wins": 0,  "podiums": 1,  "points": 62.0,  "avg_pos": 10.2},
    (2023, "Esteban Ocon"):      {"wins": 0,  "podiums": 1,  "points": 58.0,  "avg_pos": 9.3},
    (2023, "Alexander Albon"):   {"wins": 0,  "podiums": 0,  "points": 27.0,  "avg_pos": 11.1},
    (2023, "Yuki Tsunoda"):      {"wins": 0,  "podiums": 0,  "points": 17.0,  "avg_pos": 12.6},
    (2023, "Valtteri Bottas"):   {"wins": 0,  "podiums": 0,  "points": 10.0,  "avg_pos": 13.4},
    (2023, "Nico Hulkenberg"):   {"wins": 0,  "podiums": 0,  "points": 9.0,   "avg_pos": 14.3},
    (2023, "Daniel Ricciardo"):  {"wins": 0,  "podiums": 0,  "points": 6.0,   "avg_pos": 12.7},
    (2023, "Zhou Guanyu"):       {"wins": 0,  "podiums": 0,  "points": 6.0,   "avg_pos": 13.4},
    (2023, "Kevin Magnussen"):   {"wins": 0,  "podiums": 0,  "points": 3.0,   "avg_pos": 15.1},
    (2023, "Liam Lawson"):       {"wins": 0,  "podiums": 0,  "points": 2.0,   "avg_pos": 12.2},
    (2023, "Logan Sargeant"):    {"wins": 0,  "podiums": 0,  "points": 1.0,   "avg_pos": 15.2},
    # ── 2024 (24 races) ──
    (2024, "Max Verstappen"):    {"wins": 9,  "podiums": 14, "points": 437.0, "avg_pos": 3.0},
    (2024, "Lando Norris"):      {"wins": 4,  "podiums": 13, "points": 374.0, "avg_pos": 4.3},
    (2024, "Charles Leclerc"):   {"wins": 3,  "podiums": 13, "points": 356.0, "avg_pos": 3.9},
    (2024, "Oscar Piastri"):     {"wins": 2,  "podiums": 8,  "points": 292.0, "avg_pos": 5.1},
    (2024, "Carlos Sainz"):      {"wins": 2,  "podiums": 9,  "points": 290.0, "avg_pos": 4.7},
    (2024, "George Russell"):    {"wins": 2,  "podiums": 4,  "points": 245.0, "avg_pos": 5.6},
    (2024, "Lewis Hamilton"):    {"wins": 2,  "podiums": 5,  "points": 223.0, "avg_pos": 5.9},
    (2024, "Sergio Perez"):      {"wins": 0,  "podiums": 4,  "points": 152.0, "avg_pos": 7.9},
    (2024, "Fernando Alonso"):   {"wins": 0,  "podiums": 0,  "points": 70.0,  "avg_pos": 9.8},
    (2024, "Pierre Gasly"):      {"wins": 0,  "podiums": 1,  "points": 42.0,  "avg_pos": 11.5},
    (2024, "Nico Hulkenberg"):   {"wins": 0,  "podiums": 0,  "points": 41.0,  "avg_pos": 10.7},
    (2024, "Yuki Tsunoda"):      {"wins": 0,  "podiums": 0,  "points": 30.0,  "avg_pos": 11.9},
    (2024, "Lance Stroll"):      {"wins": 0,  "podiums": 0,  "points": 24.0,  "avg_pos": 12.6},
    (2024, "Esteban Ocon"):      {"wins": 0,  "podiums": 1,  "points": 23.0,  "avg_pos": 13.2},
    (2024, "Kevin Magnussen"):   {"wins": 0,  "podiums": 0,  "points": 16.0,  "avg_pos": 13.1},
    (2024, "Alexander Albon"):   {"wins": 0,  "podiums": 0,  "points": 12.0,  "avg_pos": 12.7},
    (2024, "Daniel Ricciardo"):  {"wins": 0,  "podiums": 0,  "points": 12.0,  "avg_pos": 12.8},
    (2024, "Oliver Bearman"):    {"wins": 0,  "podiums": 0,  "points": 7.0,   "avg_pos": 9.7},
    (2024, "Franco Colapinto"):  {"wins": 0,  "podiums": 0,  "points": 5.0,   "avg_pos": 11.2},
    (2024, "Zhou Guanyu"):       {"wins": 0,  "podiums": 0,  "points": 4.0,   "avg_pos": 15.2},
    (2024, "Liam Lawson"):       {"wins": 0,  "podiums": 0,  "points": 4.0,   "avg_pos": 13.5},
    (2024, "Valtteri Bottas"):   {"wins": 0,  "podiums": 0,  "points": 0.0,   "avg_pos": 15.6},
    (2024, "Logan Sargeant"):    {"wins": 0,  "podiums": 0,  "points": 0.0,   "avg_pos": 16.7},
    (2024, "Jack Doohan"):       {"wins": 0,  "podiums": 0,  "points": 0.0,   "avg_pos": 15.0},
    # ── 2025 (24 races) ──
    (2025, "Lando Norris"):              {"wins": 7,  "podiums": 18, "points": 423.0, "avg_pos": 3.6},
    (2025, "Max Verstappen"):            {"wins": 8,  "podiums": 15, "points": 421.0, "avg_pos": 3.0},
    (2025, "Oscar Piastri"):             {"wins": 7,  "podiums": 16, "points": 410.0, "avg_pos": 2.8},
    (2025, "George Russell"):            {"wins": 2,  "podiums": 9,  "points": 319.0, "avg_pos": 4.5},
    (2025, "Charles Leclerc"):           {"wins": 0,  "podiums": 7,  "points": 242.0, "avg_pos": 5.1},
    (2025, "Lewis Hamilton"):            {"wins": 0,  "podiums": 0,  "points": 156.0, "avg_pos": 7.0},
    (2025, "Andrea Kimi Antonelli"):     {"wins": 0,  "podiums": 3,  "points": 150.0, "avg_pos": 8.2},
    (2025, "Alexander Albon"):           {"wins": 0,  "podiums": 0,  "points": 73.0,  "avg_pos": 9.7},
    (2025, "Carlos Sainz"):              {"wins": 0,  "podiums": 2,  "points": 64.0,  "avg_pos": 10.8},
    (2025, "Fernando Alonso"):           {"wins": 0,  "podiums": 0,  "points": 56.0,  "avg_pos": 10.3},
    (2025, "Nico Hulkenberg"):           {"wins": 0,  "podiums": 1,  "points": 51.0,  "avg_pos": 11.4},
    (2025, "Isack Hadjar"):              {"wins": 0,  "podiums": 1,  "points": 51.0,  "avg_pos": 11.2},
    (2025, "Oliver Bearman"):            {"wins": 0,  "podiums": 0,  "points": 41.0,  "avg_pos": 10.7},
    (2025, "Liam Lawson"):               {"wins": 0,  "podiums": 0,  "points": 38.0,  "avg_pos": 11.4},
    (2025, "Esteban Ocon"):              {"wins": 0,  "podiums": 0,  "points": 38.0,  "avg_pos": 12.2},
    (2025, "Lance Stroll"):              {"wins": 0,  "podiums": 0,  "points": 33.0,  "avg_pos": 13.5},
    (2025, "Yuki Tsunoda"):              {"wins": 0,  "podiums": 0,  "points": 33.0,  "avg_pos": 12.3},
    (2025, "Pierre Gasly"):              {"wins": 0,  "podiums": 0,  "points": 22.0,  "avg_pos": 13.8},
    (2025, "Gabriel Bortoleto"):         {"wins": 0,  "podiums": 0,  "points": 19.0,  "avg_pos": 13.3},
    (2025, "Franco Colapinto"):          {"wins": 0,  "podiums": 0,  "points": 0.0,   "avg_pos": 15.8},
    (2025, "Jack Doohan"):               {"wins": 0,  "podiums": 0,  "points": 0.0,   "avg_pos": 14.8},
}

# ─── Track History & Past Winners ─────────────────────────────────────────────
# Real GP winner data 2020-2025 for preset tracks + 2026 calendar tracks

TRACK_HISTORY: dict[str, dict] = {
    "Monaco": {
        "first_gp": 1950,
        "circuit_length_km": 3.337,
        "lap_record": "1:12.909",
        "lap_record_holder": "Lewis Hamilton",
        "lap_record_year": 2021,
        "past_winners": [
            (2025, "Lando Norris", "McLaren"),
            (2024, "Charles Leclerc", "Ferrari"),
            (2023, "Max Verstappen", "Red Bull"),
            (2022, "Sergio Perez", "Red Bull"),
            (2021, "Max Verstappen", "Red Bull"),
        ],
    },
    "Silverstone": {
        "first_gp": 1950,
        "circuit_length_km": 5.891,
        "lap_record": "1:27.097",
        "lap_record_holder": "Max Verstappen",
        "lap_record_year": 2020,
        "past_winners": [
            (2025, "Oscar Piastri", "McLaren"),
            (2024, "Lewis Hamilton", "Mercedes"),
            (2023, "Max Verstappen", "Red Bull"),
            (2022, "Carlos Sainz", "Ferrari"),
            (2021, "Lewis Hamilton", "Mercedes"),
            (2020, "Lewis Hamilton", "Mercedes"),
        ],
    },
    "Monza": {
        "first_gp": 1950,
        "circuit_length_km": 5.793,
        "lap_record": "1:21.046",
        "lap_record_holder": "Rubens Barrichello",
        "lap_record_year": 2004,
        "past_winners": [
            (2025, "Oscar Piastri", "McLaren"),
            (2024, "Charles Leclerc", "Ferrari"),
            (2023, "Max Verstappen", "Red Bull"),
            (2022, "Max Verstappen", "Red Bull"),
            (2021, "Daniel Ricciardo", "McLaren"),
            (2020, "Pierre Gasly", "AlphaTauri"),
        ],
    },
    "Spa-Francorchamps": {
        "first_gp": 1950,
        "circuit_length_km": 7.004,
        "lap_record": "1:46.286",
        "lap_record_holder": "Valtteri Bottas",
        "lap_record_year": 2018,
        "past_winners": [
            (2025, "George Russell", "Mercedes"),
            (2024, "Lewis Hamilton", "Mercedes"),
            (2023, "Max Verstappen", "Red Bull"),
            (2022, "Max Verstappen", "Red Bull"),
            (2021, "Max Verstappen", "Red Bull"),
            (2020, "Lewis Hamilton", "Mercedes"),
        ],
    },
    "Suzuka": {
        "first_gp": 1987,
        "circuit_length_km": 5.807,
        "lap_record": "1:30.983",
        "lap_record_holder": "Lewis Hamilton",
        "lap_record_year": 2019,
        "past_winners": [
            (2025, "Max Verstappen", "Red Bull"),
            (2024, "Max Verstappen", "Red Bull"),
            (2023, "Max Verstappen", "Red Bull"),
            (2022, "Max Verstappen", "Red Bull"),
        ],
    },
    "Singapore": {
        "first_gp": 2008,
        "circuit_length_km": 4.940,
        "lap_record": "1:35.867",
        "lap_record_holder": "Lewis Hamilton",
        "lap_record_year": 2023,
        "past_winners": [
            (2025, "Lando Norris", "McLaren"),
            (2024, "Lando Norris", "McLaren"),
            (2023, "Carlos Sainz", "Ferrari"),
            (2022, "Sergio Perez", "Red Bull"),
        ],
    },
    "Bahrain": {
        "first_gp": 2004,
        "circuit_length_km": 5.412,
        "lap_record": "1:31.447",
        "lap_record_holder": "Pedro de la Rosa",
        "lap_record_year": 2005,
        "past_winners": [
            (2025, "Oscar Piastri", "McLaren"),
            (2024, "Max Verstappen", "Red Bull"),
            (2023, "Max Verstappen", "Red Bull"),
            (2022, "Charles Leclerc", "Ferrari"),
            (2021, "Lewis Hamilton", "Mercedes"),
            (2020, "Lewis Hamilton", "Mercedes"),
        ],
    },
    "Jeddah": {
        "first_gp": 2021,
        "circuit_length_km": 6.174,
        "lap_record": "1:30.734",
        "lap_record_holder": "Lewis Hamilton",
        "lap_record_year": 2021,
        "past_winners": [
            (2025, "Oscar Piastri", "McLaren"),
            (2024, "Max Verstappen", "Red Bull"),
            (2023, "Sergio Perez", "Red Bull"),
            (2022, "Max Verstappen", "Red Bull"),
            (2021, "Lewis Hamilton", "Mercedes"),
        ],
    },
    "COTA": {
        "first_gp": 2012,
        "circuit_length_km": 5.513,
        "lap_record": "1:36.169",
        "lap_record_holder": "Charles Leclerc",
        "lap_record_year": 2019,
        "past_winners": [
            (2025, "Max Verstappen", "Red Bull"),
            (2024, "Charles Leclerc", "Ferrari"),
            (2023, "Max Verstappen", "Red Bull"),
            (2022, "Max Verstappen", "Red Bull"),
            (2021, "Max Verstappen", "Red Bull"),
            (2020, "Lewis Hamilton", "Mercedes"),
        ],
    },
    "Interlagos": {
        "first_gp": 1973,
        "circuit_length_km": 4.309,
        "lap_record": "1:10.540",
        "lap_record_holder": "Valtteri Bottas",
        "lap_record_year": 2018,
        "past_winners": [
            (2025, "Lando Norris", "McLaren"),
            (2024, "Max Verstappen", "Red Bull"),
            (2023, "Max Verstappen", "Red Bull"),
            (2022, "George Russell", "Mercedes"),
            (2021, "Lewis Hamilton", "Mercedes"),
            (2020, "Lewis Hamilton", "Mercedes"),
        ],
    },
    "Albert Park": {
        "first_gp": 1996,
        "circuit_length_km": 5.278,
        "lap_record": "1:19.813",
        "lap_record_holder": "Charles Leclerc",
        "lap_record_year": 2024,
        "past_winners": [
            (2025, "Lando Norris", "McLaren"),
            (2024, "Carlos Sainz", "Ferrari"),
            (2023, "Max Verstappen", "Red Bull"),
            (2022, "Charles Leclerc", "Ferrari"),
        ],
    },
    "Shanghai": {
        "first_gp": 2004,
        "circuit_length_km": 5.451,
        "lap_record": "1:32.238",
        "lap_record_holder": "Michael Schumacher",
        "lap_record_year": 2004,
        "past_winners": [
            (2025, "Max Verstappen", "Red Bull"),
            (2024, "Max Verstappen", "Red Bull"),
        ],
    },
    "Miami": {
        "first_gp": 2022,
        "circuit_length_km": 5.412,
        "lap_record": "1:29.708",
        "lap_record_holder": "Max Verstappen",
        "lap_record_year": 2023,
        "past_winners": [
            (2025, "Lando Norris", "McLaren"),
            (2024, "Lando Norris", "McLaren"),
            (2023, "Sergio Perez", "Red Bull"),
            (2022, "Max Verstappen", "Red Bull"),
        ],
    },
    "Imola": {
        "first_gp": 1980,
        "circuit_length_km": 4.909,
        "lap_record": "1:15.484",
        "lap_record_holder": "Lewis Hamilton",
        "lap_record_year": 2020,
        "past_winners": [
            (2024, "Max Verstappen", "Red Bull"),
            (2022, "Max Verstappen", "Red Bull"),
            (2021, "Max Verstappen", "Red Bull"),
            (2020, "Lewis Hamilton", "Mercedes"),
        ],
    },
    "Barcelona": {
        "first_gp": 1991,
        "circuit_length_km": 4.657,
        "lap_record": "1:16.330",
        "lap_record_holder": "Max Verstappen",
        "lap_record_year": 2024,
        "past_winners": [
            (2025, "Max Verstappen", "Red Bull"),
            (2024, "Max Verstappen", "Red Bull"),
            (2023, "Max Verstappen", "Red Bull"),
            (2022, "Max Verstappen", "Red Bull"),
            (2021, "Lewis Hamilton", "Mercedes"),
            (2020, "Lewis Hamilton", "Mercedes"),
        ],
    },
    "Montreal": {
        "first_gp": 1978,
        "circuit_length_km": 4.361,
        "lap_record": "1:13.078",
        "lap_record_holder": "Valtteri Bottas",
        "lap_record_year": 2019,
        "past_winners": [
            (2025, "George Russell", "Mercedes"),
            (2024, "Max Verstappen", "Red Bull"),
            (2023, "Max Verstappen", "Red Bull"),
            (2022, "Max Verstappen", "Red Bull"),
        ],
    },
    "Red Bull Ring": {
        "first_gp": 1970,
        "circuit_length_km": 4.318,
        "lap_record": "1:05.619",
        "lap_record_holder": "Carlos Sainz",
        "lap_record_year": 2020,
        "past_winners": [
            (2025, "George Russell", "Mercedes"),
            (2024, "George Russell", "Mercedes"),
            (2023, "Max Verstappen", "Red Bull"),
            (2022, "Charles Leclerc", "Ferrari"),
            (2021, "Max Verstappen", "Red Bull"),
            (2020, "Valtteri Bottas", "Mercedes"),
        ],
    },
    "Hungaroring": {
        "first_gp": 1986,
        "circuit_length_km": 4.381,
        "lap_record": "1:16.627",
        "lap_record_holder": "Lewis Hamilton",
        "lap_record_year": 2020,
        "past_winners": [
            (2025, "Oscar Piastri", "McLaren"),
            (2024, "Oscar Piastri", "McLaren"),
            (2023, "Max Verstappen", "Red Bull"),
            (2022, "Max Verstappen", "Red Bull"),
            (2021, "Esteban Ocon", "Alpine"),
            (2020, "Lewis Hamilton", "Mercedes"),
        ],
    },
    "Zandvoort": {
        "first_gp": 1952,
        "circuit_length_km": 4.259,
        "lap_record": "1:11.097",
        "lap_record_holder": "Lewis Hamilton",
        "lap_record_year": 2021,
        "past_winners": [
            (2025, "Lando Norris", "McLaren"),
            (2024, "Lando Norris", "McLaren"),
            (2023, "Max Verstappen", "Red Bull"),
            (2022, "Max Verstappen", "Red Bull"),
            (2021, "Max Verstappen", "Red Bull"),
        ],
    },
    "Baku": {
        "first_gp": 2016,
        "circuit_length_km": 6.003,
        "lap_record": "1:43.009",
        "lap_record_holder": "Charles Leclerc",
        "lap_record_year": 2019,
        "past_winners": [
            (2025, "Lando Norris", "McLaren"),
            (2024, "Oscar Piastri", "McLaren"),
            (2023, "Sergio Perez", "Red Bull"),
            (2022, "Max Verstappen", "Red Bull"),
            (2021, "Sergio Perez", "Red Bull"),
        ],
    },
    "Mexico City": {
        "first_gp": 1963,
        "circuit_length_km": 4.304,
        "lap_record": "1:17.774",
        "lap_record_holder": "Valtteri Bottas",
        "lap_record_year": 2021,
        "past_winners": [
            (2025, "Max Verstappen", "Red Bull"),
            (2024, "Carlos Sainz", "Ferrari"),
            (2023, "Max Verstappen", "Red Bull"),
            (2022, "Max Verstappen", "Red Bull"),
            (2021, "Max Verstappen", "Red Bull"),
            (2020, "Lewis Hamilton", "Mercedes"),
        ],
    },
    "Las Vegas": {
        "first_gp": 2023,
        "circuit_length_km": 6.201,
        "lap_record": "1:32.608",
        "lap_record_holder": "Oscar Piastri",
        "lap_record_year": 2025,
        "past_winners": [
            (2025, "Oscar Piastri", "McLaren"),
            (2024, "George Russell", "Mercedes"),
            (2023, "Max Verstappen", "Red Bull"),
        ],
    },
    "Lusail": {
        "first_gp": 2021,
        "circuit_length_km": 5.419,
        "lap_record": "1:24.319",
        "lap_record_holder": "Max Verstappen",
        "lap_record_year": 2023,
        "past_winners": [
            (2025, "Lando Norris", "McLaren"),
            (2024, "Max Verstappen", "Red Bull"),
            (2023, "Max Verstappen", "Red Bull"),
            (2021, "Lewis Hamilton", "Mercedes"),
        ],
    },
    "Yas Marina": {
        "first_gp": 2009,
        "circuit_length_km": 5.281,
        "lap_record": "1:26.103",
        "lap_record_holder": "Max Verstappen",
        "lap_record_year": 2021,
        "past_winners": [
            (2025, "Oscar Piastri", "McLaren"),
            (2024, "Lando Norris", "McLaren"),
            (2023, "Max Verstappen", "Red Bull"),
            (2022, "Max Verstappen", "Red Bull"),
            (2021, "Max Verstappen", "Red Bull"),
            (2020, "Max Verstappen", "Red Bull"),
        ],
    },
}
