"""Preset data for tracks, teams, and drivers."""

from __future__ import annotations
from datetime import date

TEAM_COLORS: dict[str, str] = {
    "Red Bull": "#3671C6",
    "Ferrari": "#E8002D",
    "Mercedes": "#27F4D2",
    "McLaren": "#FF8000",
    "Aston Martin": "#229971",
    "Alpine": "#FF87BC",
    "Williams": "#64C4FF",
    "RB": "#6692FF",
    "Kick Sauber": "#52E252",
    "Haas": "#B6BABD",
}

PRESET_TRACKS = [
    {
        "name": "Monaco",
        "country": "Monaco",
        "total_laps": 78,
        "base_lap_time": 74.0,
        "pit_loss_time": 24.0,
        "drs_zones": 1,
        "overtake_difficulty": 2.0,
        "safety_car_probability": 0.05,
    },
    {
        "name": "Silverstone",
        "country": "United Kingdom",
        "total_laps": 52,
        "base_lap_time": 88.0,
        "pit_loss_time": 22.0,
        "drs_zones": 2,
        "overtake_difficulty": 0.8,
        "safety_car_probability": 0.03,
    },
    {
        "name": "Monza",
        "country": "Italy",
        "total_laps": 53,
        "base_lap_time": 82.0,
        "pit_loss_time": 25.0,
        "drs_zones": 2,
        "overtake_difficulty": 0.7,
        "safety_car_probability": 0.03,
    },
    {
        "name": "Spa-Francorchamps",
        "country": "Belgium",
        "total_laps": 44,
        "base_lap_time": 106.0,
        "pit_loss_time": 22.0,
        "drs_zones": 2,
        "overtake_difficulty": 0.8,
        "safety_car_probability": 0.04,
    },
    {
        "name": "Suzuka",
        "country": "Japan",
        "total_laps": 53,
        "base_lap_time": 91.0,
        "pit_loss_time": 23.0,
        "drs_zones": 1,
        "overtake_difficulty": 1.2,
        "safety_car_probability": 0.03,
    },
    {
        "name": "Singapore",
        "country": "Singapore",
        "total_laps": 62,
        "base_lap_time": 98.0,
        "pit_loss_time": 26.0,
        "drs_zones": 3,
        "overtake_difficulty": 1.5,
        "safety_car_probability": 0.06,
    },
    {
        "name": "Bahrain",
        "country": "Bahrain",
        "total_laps": 57,
        "base_lap_time": 92.0,
        "pit_loss_time": 22.0,
        "drs_zones": 3,
        "overtake_difficulty": 0.7,
        "safety_car_probability": 0.02,
    },
    {
        "name": "Jeddah",
        "country": "Saudi Arabia",
        "total_laps": 50,
        "base_lap_time": 89.0,
        "pit_loss_time": 23.0,
        "drs_zones": 3,
        "overtake_difficulty": 0.8,
        "safety_car_probability": 0.05,
    },
    {
        "name": "COTA",
        "country": "United States",
        "total_laps": 56,
        "base_lap_time": 97.0,
        "pit_loss_time": 22.0,
        "drs_zones": 2,
        "overtake_difficulty": 0.9,
        "safety_car_probability": 0.03,
    },
    {
        "name": "Interlagos",
        "country": "Brazil",
        "total_laps": 71,
        "base_lap_time": 72.0,
        "pit_loss_time": 22.0,
        "drs_zones": 2,
        "overtake_difficulty": 0.8,
        "safety_car_probability": 0.04,
    },
]

PRESET_DRIVERS = [
    {"name": "Max Verstappen", "team": "Red Bull", "skill": -0.8},
    {"name": "Sergio Perez", "team": "Red Bull", "skill": -0.1},
    {"name": "Charles Leclerc", "team": "Ferrari", "skill": -0.5},
    {"name": "Carlos Sainz", "team": "Ferrari", "skill": -0.3},
    {"name": "Lewis Hamilton", "team": "Mercedes", "skill": -0.5},
    {"name": "George Russell", "team": "Mercedes", "skill": -0.3},
    {"name": "Lando Norris", "team": "McLaren", "skill": -0.6},
    {"name": "Oscar Piastri", "team": "McLaren", "skill": -0.4},
    {"name": "Fernando Alonso", "team": "Aston Martin", "skill": -0.2},
    {"name": "Lance Stroll", "team": "Aston Martin", "skill": 0.1},
    {"name": "Pierre Gasly", "team": "Alpine", "skill": -0.1},
    {"name": "Esteban Ocon", "team": "Alpine", "skill": -0.0},
    {"name": "Alexander Albon", "team": "Williams", "skill": -0.1},
    {"name": "Logan Sargeant", "team": "Williams", "skill": 0.4},
    {"name": "Yuki Tsunoda", "team": "RB", "skill": -0.1},
    {"name": "Daniel Ricciardo", "team": "RB", "skill": 0.0},
    {"name": "Valtteri Bottas", "team": "Kick Sauber", "skill": 0.0},
    {"name": "Zhou Guanyu", "team": "Kick Sauber", "skill": 0.2},
    {"name": "Kevin Magnussen", "team": "Haas", "skill": 0.1},
    {"name": "Nico Hulkenberg", "team": "Haas", "skill": 0.0},
]

# ─── 2026 Season Data ───────────────────────────────────────────────────────

TEAM_COLORS_2026: dict[str, str] = {
    "Red Bull": "#3671C6",
    "Ferrari": "#E8002D",
    "Mercedes": "#27F4D2",
    "McLaren": "#FF8000",
    "Aston Martin": "#229971",
    "Alpine": "#FF87BC",
    "Williams": "#64C4FF",
    "Racing Bulls": "#6692FF",
    "Sauber": "#52E252",
    "Haas": "#B6BABD",
    "Cadillac": "#C0A44D",
}

DRIVERS_2026 = [
    {"name": "Max Verstappen", "team": "Red Bull", "skill": -0.8, "number": 1},
    {"name": "Isack Hadjar", "team": "Red Bull", "skill": 0.1, "number": 6},
    {"name": "Charles Leclerc", "team": "Ferrari", "skill": -0.5, "number": 16},
    {"name": "Lewis Hamilton", "team": "Ferrari", "skill": -0.5, "number": 44},
    {"name": "George Russell", "team": "Mercedes", "skill": -0.3, "number": 63},
    {"name": "Andrea Kimi Antonelli", "team": "Mercedes", "skill": -0.1, "number": 12},
    {"name": "Lando Norris", "team": "McLaren", "skill": -0.6, "number": 4},
    {"name": "Oscar Piastri", "team": "McLaren", "skill": -0.4, "number": 81},
    {"name": "Fernando Alonso", "team": "Aston Martin", "skill": -0.2, "number": 14},
    {"name": "Lance Stroll", "team": "Aston Martin", "skill": 0.1, "number": 18},
    {"name": "Pierre Gasly", "team": "Alpine", "skill": -0.1, "number": 10},
    {"name": "Jack Doohan", "team": "Alpine", "skill": 0.2, "number": 7},
    {"name": "Alexander Albon", "team": "Williams", "skill": -0.1, "number": 23},
    {"name": "Carlos Sainz", "team": "Williams", "skill": -0.3, "number": 55},
    {"name": "Yuki Tsunoda", "team": "Racing Bulls", "skill": -0.1, "number": 22},
    {"name": "Arvid Lindblad", "team": "Racing Bulls", "skill": 0.2, "number": 27},
    {"name": "Nico Hulkenberg", "team": "Sauber", "skill": 0.0, "number": 27},
    {"name": "Gabriel Bortoleto", "team": "Sauber", "skill": 0.1, "number": 5},
    {"name": "Esteban Ocon", "team": "Haas", "skill": 0.0, "number": 31},
    {"name": "Oliver Bearman", "team": "Haas", "skill": 0.1, "number": 87},
    {"name": "Sergio Perez", "team": "Cadillac", "skill": -0.1, "number": 11},
    {"name": "Valtteri Bottas", "team": "Cadillac", "skill": 0.0, "number": 77},
]

CALENDAR_2026 = [
    {"round": 1, "name": "Australian Grand Prix", "track": "Albert Park", "country": "Australia",
     "date": date(2026, 3, 15), "lat": -37.8497, "lon": 144.9680,
     "total_laps": 58, "base_lap_time": 80.0, "pit_loss": 22.0, "drs_zones": 3,
     "overtake_difficulty": 0.9, "sc_probability": 0.04},
    {"round": 2, "name": "Chinese Grand Prix", "track": "Shanghai", "country": "China",
     "date": date(2026, 3, 29), "lat": 31.3389, "lon": 121.2198,
     "total_laps": 56, "base_lap_time": 96.0, "pit_loss": 22.0, "drs_zones": 2,
     "overtake_difficulty": 0.8, "sc_probability": 0.03},
    {"round": 3, "name": "Japanese Grand Prix", "track": "Suzuka", "country": "Japan",
     "date": date(2026, 4, 12), "lat": 34.8431, "lon": 136.5407,
     "total_laps": 53, "base_lap_time": 91.0, "pit_loss": 23.0, "drs_zones": 1,
     "overtake_difficulty": 1.2, "sc_probability": 0.03},
    {"round": 4, "name": "Bahrain Grand Prix", "track": "Bahrain", "country": "Bahrain",
     "date": date(2026, 4, 19), "lat": 26.0325, "lon": 50.5106,
     "total_laps": 57, "base_lap_time": 92.0, "pit_loss": 22.0, "drs_zones": 3,
     "overtake_difficulty": 0.7, "sc_probability": 0.02},
    {"round": 5, "name": "Saudi Arabian Grand Prix", "track": "Jeddah", "country": "Saudi Arabia",
     "date": date(2026, 5, 3), "lat": 21.6319, "lon": 39.1044,
     "total_laps": 50, "base_lap_time": 89.0, "pit_loss": 23.0, "drs_zones": 3,
     "overtake_difficulty": 0.8, "sc_probability": 0.05},
    {"round": 6, "name": "Miami Grand Prix", "track": "Miami", "country": "United States",
     "date": date(2026, 5, 17), "lat": 25.9581, "lon": -80.2389,
     "total_laps": 57, "base_lap_time": 91.0, "pit_loss": 22.0, "drs_zones": 3,
     "overtake_difficulty": 0.8, "sc_probability": 0.04},
    {"round": 7, "name": "Emilia Romagna Grand Prix", "track": "Imola", "country": "Italy",
     "date": date(2026, 5, 31), "lat": 44.3439, "lon": 11.7167,
     "total_laps": 63, "base_lap_time": 76.0, "pit_loss": 24.0, "drs_zones": 1,
     "overtake_difficulty": 1.3, "sc_probability": 0.03},
    {"round": 8, "name": "Monaco Grand Prix", "track": "Monaco", "country": "Monaco",
     "date": date(2026, 6, 7), "lat": 43.7347, "lon": 7.4206,
     "total_laps": 78, "base_lap_time": 74.0, "pit_loss": 24.0, "drs_zones": 1,
     "overtake_difficulty": 2.0, "sc_probability": 0.05},
    {"round": 9, "name": "Spanish Grand Prix", "track": "Barcelona", "country": "Spain",
     "date": date(2026, 6, 21), "lat": 41.5700, "lon": 2.2611,
     "total_laps": 66, "base_lap_time": 78.0, "pit_loss": 22.0, "drs_zones": 2,
     "overtake_difficulty": 1.0, "sc_probability": 0.02},
    {"round": 10, "name": "Canadian Grand Prix", "track": "Montreal", "country": "Canada",
     "date": date(2026, 7, 5), "lat": 45.5017, "lon": -73.5228,
     "total_laps": 70, "base_lap_time": 75.0, "pit_loss": 22.0, "drs_zones": 2,
     "overtake_difficulty": 0.9, "sc_probability": 0.05},
    {"round": 11, "name": "Austrian Grand Prix", "track": "Red Bull Ring", "country": "Austria",
     "date": date(2026, 7, 12), "lat": 47.2197, "lon": 14.7647,
     "total_laps": 71, "base_lap_time": 66.0, "pit_loss": 21.0, "drs_zones": 2,
     "overtake_difficulty": 0.8, "sc_probability": 0.03},
    {"round": 12, "name": "British Grand Prix", "track": "Silverstone", "country": "United Kingdom",
     "date": date(2026, 7, 19), "lat": 52.0786, "lon": -1.0169,
     "total_laps": 52, "base_lap_time": 88.0, "pit_loss": 22.0, "drs_zones": 2,
     "overtake_difficulty": 0.8, "sc_probability": 0.03},
    {"round": 13, "name": "Belgian Grand Prix", "track": "Spa-Francorchamps", "country": "Belgium",
     "date": date(2026, 8, 2), "lat": 50.4372, "lon": 5.9714,
     "total_laps": 44, "base_lap_time": 106.0, "pit_loss": 22.0, "drs_zones": 2,
     "overtake_difficulty": 0.8, "sc_probability": 0.04},
    {"round": 14, "name": "Hungarian Grand Prix", "track": "Hungaroring", "country": "Hungary",
     "date": date(2026, 8, 9), "lat": 47.5789, "lon": 19.2486,
     "total_laps": 70, "base_lap_time": 79.0, "pit_loss": 23.0, "drs_zones": 1,
     "overtake_difficulty": 1.5, "sc_probability": 0.02},
    {"round": 15, "name": "Dutch Grand Prix", "track": "Zandvoort", "country": "Netherlands",
     "date": date(2026, 8, 30), "lat": 52.3888, "lon": 4.5409,
     "total_laps": 72, "base_lap_time": 72.0, "pit_loss": 22.0, "drs_zones": 1,
     "overtake_difficulty": 1.6, "sc_probability": 0.03},
    {"round": 16, "name": "Italian Grand Prix", "track": "Monza", "country": "Italy",
     "date": date(2026, 9, 6), "lat": 45.6156, "lon": 9.2811,
     "total_laps": 53, "base_lap_time": 82.0, "pit_loss": 25.0, "drs_zones": 2,
     "overtake_difficulty": 0.7, "sc_probability": 0.03},
    {"round": 17, "name": "Azerbaijan Grand Prix", "track": "Baku", "country": "Azerbaijan",
     "date": date(2026, 9, 20), "lat": 40.3725, "lon": 49.8533,
     "total_laps": 51, "base_lap_time": 103.0, "pit_loss": 24.0, "drs_zones": 2,
     "overtake_difficulty": 0.8, "sc_probability": 0.06},
    {"round": 18, "name": "Singapore Grand Prix", "track": "Singapore", "country": "Singapore",
     "date": date(2026, 10, 4), "lat": 1.2914, "lon": 103.8640,
     "total_laps": 62, "base_lap_time": 98.0, "pit_loss": 26.0, "drs_zones": 3,
     "overtake_difficulty": 1.5, "sc_probability": 0.06},
    {"round": 19, "name": "United States Grand Prix", "track": "COTA", "country": "United States",
     "date": date(2026, 10, 18), "lat": 30.1328, "lon": -97.6411,
     "total_laps": 56, "base_lap_time": 97.0, "pit_loss": 22.0, "drs_zones": 2,
     "overtake_difficulty": 0.9, "sc_probability": 0.03},
    {"round": 20, "name": "Mexico City Grand Prix", "track": "Mexico City", "country": "Mexico",
     "date": date(2026, 10, 25), "lat": 19.4042, "lon": -99.0907,
     "total_laps": 71, "base_lap_time": 78.0, "pit_loss": 23.0, "drs_zones": 3,
     "overtake_difficulty": 0.8, "sc_probability": 0.04},
    {"round": 21, "name": "Brazilian Grand Prix", "track": "Interlagos", "country": "Brazil",
     "date": date(2026, 11, 8), "lat": -23.7036, "lon": -46.6997,
     "total_laps": 71, "base_lap_time": 72.0, "pit_loss": 22.0, "drs_zones": 2,
     "overtake_difficulty": 0.8, "sc_probability": 0.04},
    {"round": 22, "name": "Las Vegas Grand Prix", "track": "Las Vegas", "country": "United States",
     "date": date(2026, 11, 22), "lat": 36.1147, "lon": -115.1728,
     "total_laps": 50, "base_lap_time": 95.0, "pit_loss": 23.0, "drs_zones": 2,
     "overtake_difficulty": 0.8, "sc_probability": 0.04},
    {"round": 23, "name": "Qatar Grand Prix", "track": "Lusail", "country": "Qatar",
     "date": date(2026, 11, 29), "lat": 25.4900, "lon": 51.4542,
     "total_laps": 57, "base_lap_time": 86.0, "pit_loss": 22.0, "drs_zones": 2,
     "overtake_difficulty": 0.8, "sc_probability": 0.03},
    {"round": 24, "name": "Abu Dhabi Grand Prix", "track": "Yas Marina", "country": "UAE",
     "date": date(2026, 12, 6), "lat": 24.4672, "lon": 54.6031,
     "total_laps": 58, "base_lap_time": 87.0, "pit_loss": 22.0, "drs_zones": 2,
     "overtake_difficulty": 0.9, "sc_probability": 0.02},
]

POINTS_SYSTEM: dict[int, int] = {
    1: 25, 2: 18, 3: 15, 4: 12, 5: 10, 6: 8, 7: 6, 8: 4, 9: 2, 10: 1,
}
